export type Lang = "ko" | "en" | "ja";

export interface EndingMetaEntry {
  title: string;
  condition: string;
}

export const ENDING_META: Record<Lang, Record<string, EndingMetaEntry>> = {
  ko: {
    normal: { title: "일반 엔딩", condition: "100일 생존" },
    bankrupt: { title: "파산 엔딩", condition: "크레딧 0" },
    stress: { title: "스트레스 엔딩", condition: "스트레스 100을 10일 유지" },
    "normal.default": { title: "생존(디폴트)", condition: "100일 생존" },
    "normal.earth_destroy": { title: "지구파괴", condition: "100일 + 스테이지 39+" },
    "normal.atmosphere": { title: "대기권 돌파", condition: "100일 + 스테이지 25+" },
    "normal.planet_scale": { title: "행성급 스케일", condition: "100일 + 스테이지 50+" },
    "normal.malnutrition": { title: "영양실조", condition: "100일 + 밥 <= 20회" },
    "normal.overnutrition": { title: "영양과다", condition: "100일 + 밥 >= 180회" },
    "normal.workaholic": { title: "워커홀릭", condition: "100일 + 일 >= 200회" },
    "normal.social_king": { title: "인맥왕", condition: "100일 + 게스트 >= 220회" },
    "normal.worklife_balance": { title: "워라밸 마스터", condition: "100일 + 행동 균형" },
    "normal.malang": { title: "말랑이", condition: "100일 + 모모이+아리스 >= 100회" },
    "bankrupt.default": { title: "파산(디폴트)", condition: "크레딧 0" },
    "bankrupt.koyuki_reflect": { title: "코유키 반성방", condition: "파산 + 코유키 쪽박 >= 5" },
    "bankrupt.overspend": { title: "과소비", condition: "파산 + 밥 비율 >= 60%" },
    "bankrupt.financial_crisis": { title: "금융위기", condition: "파산 + 스테이지 20+" },
    "bankrupt.global_crisis": { title: "글로벌 금융위기", condition: "파산 + 스테이지 30+" },
    "stress.default": { title: "과로(디폴트)", condition: "스트레스 100을 10일 유지" },
    "stress.early_break": { title: "초반 붕괴", condition: "과로 + 20일 이하" },
    "stress.late_fizzle": { title: "용두사미", condition: "과로 + 90일 이상" },
    "special.marriage": { title: "결혼", condition: "선생님 >= 100회(즉시)" },
    "special.shadow_time": { title: "쉐도우타임", condition: "00:00에 엔딩(즉시)" },
    "any.lucky_seven": { title: "럭키세븐", condition: "엔딩 시 허벅지 숫자=7만" },
    "any.all_nines": { title: "비둘기야 밥먹자", condition: "엔딩 시 허벅지 숫자=9만" },
    "any.seq_12345_thigh": { title: "어케했누", condition: "엔딩 시 허벅지=12345" },
    "any.seq_123456_credit": { title: "어케했누2", condition: "엔딩 시 크레딧=123456" },
    "any.morning_only_eat": { title: "아침 공작", condition: "밥은 아침에만" },
    "any.noon_only_eat": { title: "점심 호랑이", condition: "밥은 점심에만" },
    "any.evening_only_eat": { title: "밤 가이!!!", condition: "밥은 저녁에만" },
    unknown: { title: "알 수 없는 엔딩", condition: "조건 정보 없음" },
  },
  en: {
    normal: { title: "Normal Ending", condition: "Survive 100 days" },
    bankrupt: { title: "Bankruptcy Ending", condition: "Credits reach 0" },
    stress: { title: "Stress Ending", condition: "Stress 100 for 10 days" },
    "normal.default": { title: "Survivor (Default)", condition: "Survive 100 days" },
    "normal.earth_destroy": { title: "Earth Destroy", condition: "100 days + Stage >= 39" },
    "normal.atmosphere": { title: "Atmosphere Breakthrough", condition: "100 days + Stage >= 25" },
    "normal.planet_scale": { title: "Planet Scale", condition: "100 days + Stage >= 50" },
    "normal.malnutrition": { title: "Malnutrition", condition: "100 days + Eat <= 20" },
    "normal.overnutrition": { title: "Overnutrition", condition: "100 days + Eat >= 180" },
    "normal.workaholic": { title: "Workaholic", condition: "100 days + Work >= 200" },
    "normal.social_king": { title: "Networking King", condition: "100 days + Guest >= 220" },
    "normal.worklife_balance": { title: "Work-Life Master", condition: "100 days + Balanced actions" },
    "normal.malang": { title: "Softie", condition: "100 days + Momoi+Aris >= 100" },
    "bankrupt.default": { title: "Bankrupt (Default)", condition: "Credits reach 0" },
    "bankrupt.koyuki_reflect": { title: "Koyuki Reflection Room", condition: "Bankrupt + Koyuki losses >= 5" },
    "bankrupt.overspend": { title: "Overspending", condition: "Bankrupt + Eat ratio >= 60%" },
    "bankrupt.financial_crisis": { title: "Financial Crisis", condition: "Bankrupt + Stage >= 20" },
    "bankrupt.global_crisis": { title: "Global Financial Crisis", condition: "Bankrupt + Stage >= 30" },
    "stress.default": { title: "Overwork (Default)", condition: "Stress 100 for 10 days" },
    "stress.early_break": { title: "Early Break", condition: "Overwork + Day <= 20" },
    "stress.late_fizzle": { title: "Late Fizzle", condition: "Overwork + Day >= 90" },
    "special.marriage": { title: "Marriage", condition: "Sensei >= 100 (instant)" },
    "special.shadow_time": { title: "Shadow Time", condition: "End at 00:00 (instant)" },
    "any.lucky_seven": { title: "Lucky Seven", condition: "End with all thigh digits = 7" },
    "any.all_nines": { title: "Let's Feed Pigeons", condition: "End with all thigh digits = 9" },
    "any.seq_12345_thigh": { title: "How Did You Do That", condition: "End with thigh = 12345" },
    "any.seq_123456_credit": { title: "How Did You Do That 2", condition: "End with credits = 123456" },
    "any.morning_only_eat": { title: "Morning Peacock", condition: "Eat only in Morning" },
    "any.noon_only_eat": { title: "Noon Tiger", condition: "Eat only at Noon" },
    "any.evening_only_eat": { title: "Night Guy!!!", condition: "Eat only in Evening" },
    unknown: { title: "Unknown Ending", condition: "Condition unknown" },
  },
  ja: {
    normal: { title: "ノーマルエンド", condition: "100日生存" },
    bankrupt: { title: "破産エンド", condition: "クレジット0" },
    stress: { title: "ストレスエンド", condition: "ストレス100を10日維持" },
    "normal.default": { title: "生存（デフォルト）", condition: "100日生存" },
    "normal.earth_destroy": { title: "地球崩壊", condition: "100日＋ステージ39以上" },
    "normal.atmosphere": { title: "大気圏突破", condition: "100日＋ステージ25以上" },
    "normal.planet_scale": { title: "惑星級スケール", condition: "100日＋ステージ50以上" },
    "normal.malnutrition": { title: "栄養失調", condition: "100日＋食事20回以下" },
    "normal.overnutrition": { title: "栄養過多", condition: "100日＋食事180回以上" },
    "normal.workaholic": { title: "ワーカホリック", condition: "100日＋仕事200回以上" },
    "normal.social_king": { title: "人脈王", condition: "100日＋ゲスト220回以上" },
    "normal.worklife_balance": { title: "ワークライフマスター", condition: "100日＋行動バランス" },
    "normal.malang": { title: "ぷにぷに", condition: "100日＋モモイ+アリス100回以上" },
    "bankrupt.default": { title: "破産（デフォルト）", condition: "クレジット0" },
    "bankrupt.koyuki_reflect": { title: "コユキ反省部屋", condition: "破産＋コユキ損5回以上" },
    "bankrupt.overspend": { title: "浪費", condition: "破産＋食事比率60%以上" },
    "bankrupt.financial_crisis": { title: "金融危機", condition: "破産＋ステージ20以上" },
    "bankrupt.global_crisis": { title: "世界金融危機", condition: "破産＋ステージ30以上" },
    "stress.default": { title: "過労（デフォルト）", condition: "ストレス100を10日維持" },
    "stress.early_break": { title: "序盤崩壊", condition: "過労＋20日以内" },
    "stress.late_fizzle": { title: "竜頭蛇尾", condition: "過労＋90日以上" },
    "special.marriage": { title: "結婚", condition: "先生100回（即時）" },
    "special.shadow_time": { title: "シャドウタイム", condition: "0:00に終了（即時）" },
    "any.lucky_seven": { title: "ラッキーセブン", condition: "終了時 太もも数字が全部7" },
    "any.all_nines": { title: "ハトにごはん", condition: "終了時 太もも数字が全部9" },
    "any.seq_12345_thigh": { title: "どうやったの", condition: "終了時 太もも=12345" },
    "any.seq_123456_credit": { title: "どうやったの2", condition: "終了時 クレジット=123456" },
    "any.morning_only_eat": { title: "朝の孔雀", condition: "食事は朝のみ" },
    "any.noon_only_eat": { title: "昼の虎", condition: "食事は昼のみ" },
    "any.evening_only_eat": { title: "夜のガイ!!!", condition: "食事は夜のみ" },
    unknown: { title: "不明なエンディング", condition: "条件情報なし" },
  },
};

export function getEndingTitle(endingId: string, lang: Lang): string {
  return ENDING_META[lang][endingId]?.title ?? ENDING_META.en[endingId]?.title ?? endingId;
}

export function getEndingCondition(endingId: string, lang: Lang): string {
  return ENDING_META[lang][endingId]?.condition ?? ENDING_META.en[endingId]?.condition ?? endingId;
}

