export type Lang = "ko" | "en" | "ja";

export interface EndingMetaEntry {
  title: string;
  condition: string;
}

export const ENDING_META: Record<Lang, Record<string, EndingMetaEntry>> = {
  ko: {
    normal: { title: "일반 엔딩", condition: "100일 동안 살아남는다." },
    bankrupt: { title: "파산 엔딩", condition: "크레딧이 바닥나 파산한다." },
    stress: { title: "스트레스 엔딩", condition: "스트레스 100 상태를 10일 연속 유지한다." },
    "normal.default": { title: "100일 생존", condition: "100일 동안 살아남는다." },
    "normal.earth_destroy": { title: "지구파괴", condition: "100일 동안 살아남고 스테이지가 39 이상." },
    "normal.atmosphere": { title: "대기권 돌파", condition: "100일 동안 살아남고 스테이지가 25 이상." },
    "normal.planet_scale": { title: "행성급 스케일", condition: "100일 동안 살아남고 스테이지가 50 이상." },
    "normal.malnutrition": { title: "영양실조", condition: "100일 동안 살아남고 밥먹기 횟수가 20회 이하." },
    "normal.overnutrition": { title: "영양과다", condition: "100일 동안 살아남고 밥먹기 횟수가 100회 이상." },
    "normal.workaholic": { title: "워커홀릭", condition: "100일 동안 살아남고 일하기 횟수가 100회 이상." },
    "normal.social_king": { title: "인맥왕", condition: "100일 동안 살아남고 게스트를 180회 이상 만난다." },
    "normal.worklife_balance": { title: "워라밸 마스터", condition: "행동 선택이 전체적으로 균형을 이룬다." },
    "normal.malang": { title: "말랑이", condition: "100일 동안 살아남고 모모이와 아리스를 합쳐 60회 이상 만난다." },
    "bankrupt.default": { title: "밀레니엄 파산", condition: "크레딧이 바닥나 밀레니엄이 파산한다." },
    "bankrupt.koyuki_reflect": { title: "코유키 반성방", condition: "파산한 상태에서 코유키 쪽박이 10회 이상." },
    "bankrupt.overspend": { title: "과소비", condition: "파산한 상태에서 밥먹기 비율이 60퍼센트 이상." },
    "bankrupt.financial_crisis": { title: "금융위기", condition: "파산한 상태에서 스테이지가 20 이상." },
    "bankrupt.global_crisis": { title: "글로벌 금융위기", condition: "파산한 상태에서 스테이지가 30 이상." },
    "stress.default": { title: "과로", condition: "스트레스 100 상태를 10일 연속 유지한다." },
    "stress.early_break": { title: "초반 붕괴", condition: "스트레스 엔딩 조건을 만족한 채 20일 이내에 끝난다." },
    "stress.late_fizzle": { title: "용두사미", condition: "스트레스 엔딩 조건을 만족한 채 90일 이후에 끝난다." },
    "special.marriage": { title: "결혼", condition: "선생님을 30회 이상 만나면 즉시 발동한다. 이 엔딩은 한 번만 달성할 수 있다." },
    "special.shadow_time": { title: "섀도우타임", condition: "자정 00시 00분에 엔딩에 도달한다." },
    "any.lucky_seven": { title: "럭키세븐", condition: "엔딩 시 허벅지 수치의 모든 숫자가 7이다." },
    "any.all_nines": { title: "비둘기야 밥먹자", condition: "엔딩 시 허벅지 수치의 모든 숫자가 9이다." },
    "any.seq_12345_thigh": { title: "어케했누", condition: "엔딩 시 허벅지 수치가 정확히 12345이다." },
    "any.seq_123456_credit": { title: "어케했누2", condition: "엔딩 시 크레딧 수치가 정확히 123456이다." },
    "any.morning_only_eat": { title: "아침 공작", condition: "밥먹기를 아침에만 한다." },
    "any.noon_only_eat": { title: "점심 호랑이", condition: "밥먹기를 점심에만 한다." },
    "any.evening_only_eat": { title: "밤 가이!!!", condition: "밥먹기를 저녁에만 한다." },
    "any.noa_marriage": { title: "노아와 결혼", condition: "노아를 30회 이상 만나면 즉시 발동한다. 이 엔딩은 한 번만 달성할 수 있다." },
    "any.foodie": { title: "금강산도 식후경", condition: "1일차의 아침, 점심, 저녁 행동을 모두 밥먹기로 선택한다." },
    "any.num_1557": { title: "1557", condition: "엔딩 시 허벅지 또는 크레딧 수치에 1557이 포함된다." },
    unknown: { title: "알 수 없는 엔딩", condition: "조건 정보를 확인할 수 없다." },
  },
  en: {
    normal: { title: "Normal Ending", condition: "Survive for 100 days." },
    bankrupt: { title: "Bankruptcy Ending", condition: "Run out of credits and go bankrupt." },
    stress: { title: "Stress Ending", condition: "Keep stress at 100 for 10 consecutive days." },
    "normal.default": { title: "Millenium Survivor", condition: "Survive for 100 days." },
    "normal.earth_destroy": { title: "Earth Destroy", condition: "Survive for 100 days and reach stage 39 or higher." },
    "normal.atmosphere": { title: "Atmosphere Breakthrough", condition: "Survive for 100 days and reach stage 25 or higher." },
    "normal.planet_scale": { title: "Planet Scale", condition: "Survive for 100 days and reach stage 50 or higher." },
    "normal.malnutrition": { title: "Malnutrition", condition: "Survive for 100 days and eat 20 times or less." },
    "normal.overnutrition": { title: "Overnutrition", condition: "Survive for 100 days and eat 100 times or more." },
    "normal.workaholic": { title: "Workaholic", condition: "Survive for 100 days and work 100 times or more." },
    "normal.social_king": { title: "Networking King", condition: "Survive for 100 days and meet guests at least 180 times." },
    "normal.worklife_balance": { title: "Work-Life Master", condition: "Keep your action choices balanced overall." },
    "normal.malang": { title: "Softie", condition: "Survive for 100 days and meet Momoi and Aris a combined 60 times or more." },
    "bankrupt.default": { title: "Millenium Bankruptcy", condition: "Run out of credits and make Millennium go bankrupt." },
    "bankrupt.koyuki_reflect": { title: "Koyuki Reflection Room", condition: "Go bankrupt after getting Koyuki loss outcomes 10 times or more." },
    "bankrupt.overspend": { title: "Overspending", condition: "Go bankrupt while meal actions account for at least 60 percent." },
    "bankrupt.financial_crisis": { title: "Financial Crisis", condition: "Go bankrupt while at stage 20 or higher." },
    "bankrupt.global_crisis": { title: "Global Financial Crisis", condition: "Go bankrupt while at stage 30 or higher." },
    "stress.default": { title: "Overworked", condition: "Keep stress at 100 for 10 consecutive days." },
    "stress.early_break": { title: "Early Break", condition: "Meet the overwork ending condition and finish on day 20 or earlier." },
    "stress.late_fizzle": { title: "Late Fizzle", condition: "Meet the overwork ending condition and finish on day 90 or later." },
    "special.marriage": { title: "Marriage", condition: "Triggers immediately after meeting Sensei 30 times or more. This ending can be achieved only once." },
    "special.shadow_time": { title: "Shadow Time", condition: "Reach an ending exactly at midnight (00:00)." },
    "any.lucky_seven": { title: "Lucky Seven", condition: "At run end, every digit of your thigh value is 7." },
    "any.all_nines": { title: "Let's Feed Pigeons", condition: "At run end, every digit of your thigh value is 9." },
    "any.seq_12345_thigh": { title: "How Did You Do That", condition: "At run end, your thigh value is exactly 12345." },
    "any.seq_123456_credit": { title: "How Did You Do That 2", condition: "At run end, your credit value is exactly 123456." },
    "any.morning_only_eat": { title: "Morning Peacock", condition: "Choose Eat only in the morning action slot." },
    "any.noon_only_eat": { title: "Noon Tiger", condition: "Choose Eat only in the noon action slot." },
    "any.evening_only_eat": { title: "Night Guy!!!", condition: "Choose Eat only in the evening action slot." },
    "any.noa_marriage": { title: "Noa Marriage", condition: "Triggers immediately after meeting Noa 30 times or more. This ending can be achieved only once." },
    "any.foodie": { title: "Foodie", condition: "On day 1, choose Eat in the morning, noon, and evening." },
    "any.num_1557": { title: "1557", condition: "At run end, your thigh or credit value contains the sequence 1557." },
    unknown: { title: "Unknown Ending", condition: "No condition information is available." },
  },
  ja: {
    normal: { title: "ノーマルエンド", condition: "100日間生き残る。" },
    bankrupt: { title: "破産エンド", condition: "クレジットが尽きて破産する。" },
    stress: { title: "ストレスエンド", condition: "ストレス100の状態を10日連続で維持する。" },
    "normal.default": { title: "生存", condition: "100日間生き残る。" },
    "normal.earth_destroy": { title: "地球崩壊", condition: "100日間生き残り、ステージ39以上に到達する。" },
    "normal.atmosphere": { title: "大気圏突破", condition: "100日間生き残り、ステージ25以上に到達する。" },
    "normal.planet_scale": { title: "惑星級スケール", condition: "100日間生き残り、ステージ50以上に到達する。" },
    "normal.malnutrition": { title: "栄養失調", condition: "100日間生き残り、食事回数が20回以下になる。" },
    "normal.overnutrition": { title: "栄養過多", condition: "100日間生き残り、食事回数が100回以上になる。" },
    "normal.workaholic": { title: "ワーカホリック", condition: "100日間生き残り、仕事回数が100回以上になる。" },
    "normal.social_king": { title: "人脈王", condition: "100日間生き残り、ゲストと180回以上会う。" },
    "normal.worklife_balance": { title: "ワークライフマスター", condition: "行動選択を全体的にバランスよく保つ。" },
    "normal.malang": { title: "ぷにぷに", condition: "100日間生き残り、モモイとアリスの合計回数が60回以上になる。" },
    "bankrupt.default": { title: "破産", condition: "クレジットが尽きてミレニアムが破産する。" },
    "bankrupt.koyuki_reflect": { title: "コユキ反省部屋", condition: "破産したうえで、コユキのハズレ結果が10回以上になる。" },
    "bankrupt.overspend": { title: "浪費", condition: "破産したうえで、食事行動の比率が60パーセント以上になる。" },
    "bankrupt.financial_crisis": { title: "金融危機", condition: "破産したうえで、ステージ20以上に到達する。" },
    "bankrupt.global_crisis": { title: "世界金融危機", condition: "破産したうえで、ステージ30以上に到達する。" },
    "stress.default": { title: "過労", condition: "ストレス100の状態を10日連続で維持する。" },
    "stress.early_break": { title: "序盤崩壊", condition: "過労エンド条件を満たした状態で、20日以内に終了する。" },
    "stress.late_fizzle": { title: "竜頭蛇尾", condition: "過労エンド条件を満たした状態で、90日以降に終了する。" },
    "special.marriage": { title: "結婚", condition: "先生と30回以上会うと即時に発動する。このエンディングは一度だけ達成できる。" },
    "special.shadow_time": { title: "シャドウタイム", condition: "深夜0時00分ちょうどにエンディングへ到達する。" },
    "any.lucky_seven": { title: "ラッキーセブン", condition: "終了時、太ももの数値のすべての桁が7になる。" },
    "any.all_nines": { title: "ハトにごはん", condition: "終了時、太ももの数値のすべての桁が9になる。" },
    "any.seq_12345_thigh": { title: "どうやったの", condition: "終了時、太ももの数値がちょうど12345になる。" },
    "any.seq_123456_credit": { title: "どうやったの2", condition: "終了時、クレジットの数値がちょうど123456になる。" },
    "any.morning_only_eat": { title: "朝孔雀", condition: "食事を朝の行動枠でのみ選ぶ。" },
    "any.noon_only_eat": { title: "昼虎", condition: "食事を昼の行動枠でのみ選ぶ。" },
    "any.evening_only_eat": { title: "夜ガイ!!!", condition: "食事を夜の行動枠でのみ選ぶ。" },
    "any.noa_marriage": { title: "Noa Marriage", condition: "ノアと30回以上会うと即時に発動する。このエンディングは一度だけ達成できる。" },
    "any.foodie": { title: "Foodie", condition: "1日目の朝・昼・夜の3行動をすべて食事にする。" },
    "any.num_1557": { title: "1557", condition: "終了時、太ももかクレジットの数値に「1557」の並びが含まれる。" },
    unknown: { title: "不明なエンディング", condition: "条件情報を確認できない。" },
  },
};

export function getEndingTitle(endingId: string, lang: Lang): string {
  return ENDING_META[lang][endingId]?.title ?? ENDING_META.en[endingId]?.title ?? endingId;
}

export function getEndingCondition(endingId: string, lang: Lang): string {
  return ENDING_META[lang][endingId]?.condition ?? ENDING_META.en[endingId]?.condition ?? endingId;
}
