export type Lang = "ko" | "en" | "ja";

export const ENDING_TITLES: Record<Lang, Record<string, string>> = {
  ko: {
    normal: "일반 엔딩",
    bankrupt: "파산 엔딩",
    stress: "스트레스 엔딩",
    "special.shadow_time": "쉐도우타임",
    "special.marriage": "결혼",
    "any.lucky_seven": "럭키세븐",
    "any.all_nines": "비둘기야 밥먹자",
    "any.seq_12345_thigh": "어케했누",
    "any.seq_123456_credit": "어케했누2",
    "any.morning_only_eat": "아침 공작",
    "any.noon_only_eat": "점심 호랑이",
    "any.evening_only_eat": "밤 가이!!!",
    "normal.planet_scale": "행성급 스케일",
    "normal.earth_destroy": "지구파괴",
    "normal.atmosphere": "대기권 돌파",
    "normal.malang": "말랑이",
    "normal.worklife_balance": "워라밸 마스터",
    "normal.social_king": "인맥왕",
    "normal.workaholic": "워커홀릭",
    "normal.overnutrition": "영양과다",
    "normal.malnutrition": "영양실조",
    "normal.default": "생존(디폴트)",
    "bankrupt.global_crisis": "글로벌 금융위기",
    "bankrupt.koyuki_reflect": "코유키 반성방",
    "bankrupt.financial_crisis": "금융위기",
    "bankrupt.overspend": "과소비",
    "bankrupt.default": "파산(디폴트)",
    "stress.late_fizzle": "용두사미",
    "stress.early_break": "초반 붕괴",
    "stress.default": "과로(디폴트)",
    unknown: "알 수 없는 엔딩",
  },
  en: {
    normal: "Normal Ending",
    bankrupt: "Bankruptcy Ending",
    stress: "Stress Ending",
    "special.shadow_time": "Shadow Time",
    "special.marriage": "Marriage",
    "any.lucky_seven": "Lucky Seven",
    "any.all_nines": "Let's Feed Pigeons",
    "any.seq_12345_thigh": "How Did You Do That",
    "any.seq_123456_credit": "How Did You Do That 2",
    "any.morning_only_eat": "Morning Peacock",
    "any.noon_only_eat": "Noon Tiger",
    "any.evening_only_eat": "Night Guy!!!",
    "normal.planet_scale": "Planet Scale",
    "normal.earth_destroy": "Earth Destroy",
    "normal.atmosphere": "Atmosphere Breakthrough",
    "normal.malang": "Softie",
    "normal.worklife_balance": "Work-Life Master",
    "normal.social_king": "Networking King",
    "normal.workaholic": "Workaholic",
    "normal.overnutrition": "Overnutrition",
    "normal.malnutrition": "Malnutrition",
    "normal.default": "Survivor (Default)",
    "bankrupt.global_crisis": "Global Financial Crisis",
    "bankrupt.koyuki_reflect": "Koyuki Reflection Room",
    "bankrupt.financial_crisis": "Financial Crisis",
    "bankrupt.overspend": "Overspending",
    "bankrupt.default": "Bankrupt (Default)",
    "stress.late_fizzle": "Late Fizzle",
    "stress.early_break": "Early Break",
    "stress.default": "Overwork (Default)",
    unknown: "Unknown Ending",
  },
  ja: {
    normal: "ノーマルエンド",
    bankrupt: "破産エンド",
    stress: "ストレスエンド",
    "special.shadow_time": "シャドウタイム",
    "special.marriage": "結婚",
    "any.lucky_seven": "ラッキーセブン",
    "any.all_nines": "ハトにごはん",
    "any.seq_12345_thigh": "どうやったの",
    "any.seq_123456_credit": "どうやったの2",
    "any.morning_only_eat": "朝の孔雀",
    "any.noon_only_eat": "昼の虎",
    "any.evening_only_eat": "夜のガイ!!!",
    "normal.planet_scale": "惑星級スケール",
    "normal.earth_destroy": "地球崩壊",
    "normal.atmosphere": "大気圏突破",
    "normal.malang": "ぷにぷに",
    "normal.worklife_balance": "ワークライフマスター",
    "normal.social_king": "人脈王",
    "normal.workaholic": "ワーカホリック",
    "normal.overnutrition": "栄養過多",
    "normal.malnutrition": "栄養失調",
    "normal.default": "生存（デフォルト）",
    "bankrupt.global_crisis": "世界金融危機",
    "bankrupt.koyuki_reflect": "コユキ反省部屋",
    "bankrupt.financial_crisis": "金融危機",
    "bankrupt.overspend": "浪費",
    "bankrupt.default": "破産（デフォルト）",
    "stress.late_fizzle": "竜頭蛇尾",
    "stress.early_break": "序盤崩壊",
    "stress.default": "過労（デフォルト）",
    unknown: "不明なエンディング",
  },
};

export function getEndingTitle(endingId: string, lang: Lang): string {
  return ENDING_TITLES[lang][endingId] ?? ENDING_TITLES.en[endingId] ?? endingId;
}

